### ISSUE TITLE
Session problem

### ISSUE THREAD

**Issue by aouniradouan** [Madeorsk/nocsrf#1]
Hi sir, thank you for this package
i have a problem in my project it show me this 

`session_start(): Cannot start session when headers already sent`
In
`/home1/host/public_html/--/root/vendor/madeorsk/session/src/Session/Session.php`
How can i solve this problem please !

**Comment by Madeorsk** [comment]
Hi

NoCsrf should be instantiated before any response is sent to the client, if you use the session key storage.

Make sure that you are not sending any header or echoing anything before instantiating NoCsrf.
